spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:saas_db}
    username: ${POSTGRES_USER:saas_user}
    password: ${POSTGRES_PASSWORD:saas_pass}
    driver-class-name: org.postgresql.Driver

  redis:
    data:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
