spring:
  profiles:
    active: dev # Default to dev unless overridden with --spring.profiles.active=prod
---
# Dev profile: load .env automatically
spring:
  config:
    import: optional:file:.env[.properties]
  config.activate.on-profile: dev

  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  redis:
    data:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  
security:
  config:
    csrf:
      enabled: false

---
# Prod profile: no .env, rely on real env vars
spring:
  config.activate.on-profile: prod

  application:
    name: backend
